### ISSUE TITLE
JS Color palette too similar?

### ISSUE THREAD

**Issue by martifenosa** [endormi/vscode-2077-theme#14]
Loving the theme!

There is just one thing that is bothering me, the .js files blue palette is way too similar for my taste.

For instance, those two shades of blue are hard to tell one from the other. 
![Screenshot 2020-02-17 at 14 06 17](https://user-images.githubusercontent.com/12196520/74656764-1902ab80-518f-11ea-9ad9-ce76d6547a32.png)

Same with comments:
![Screenshot 2020-02-17 at 14 10 05](https://user-images.githubusercontent.com/12196520/74656833-3a639780-518f-11ea-9a99-1d58650a5072.png)

Great work! Really liked the Terminal palette ;)

**Comment by endormi** [comment]
Thanks for using my theme!

I agree with the two shades of blue and will be working on a fix for it, should it be darker or lighter in your opinion?

The comments, however I have had previous issues (see #6) with it and came to that result, so I'm going to be thinking about that for a little bit. I'll update you about it shortly.

And thanks, I'm glad you're enjoying the Terminal palette!

**Comment by martifenosa** [comment]
'this' it's often used either with a function or with a variable so ideally it should be different to both of them. 

The variables now are that nice neon magenta, so another solution may be to change the functions color. Functions are very important code so an strong or easy to spot color could do the trick. Maybe adding more yellow stuff? Or some neon green? I don't know, just saying what comes to mind in here. 

I love the way the yellow pops and it's easy to see, in my opinion functions should be something similar. 

Keep going! This game is the first one ever I bought before release, lets keep the hype until September :P

**Comment by endormi** [comment]
I personally think that the functions, vars and consts should stay the same color (not as in purple) as I did it on purpose (I tried the yellow color for functions and didn't like it), but I'll look into it. For the comments though, I'm thinking about letting them be as is.

Haha. me too. I pre-ordered a while back.

**Comment by endormi** [comment]
Fixed with `v.1.4.4`.
