### ISSUE TITLE
Add indent guides that are always visible

### ISSUE THREAD

**Issue by kybouw** [endormi/vscode-2077-theme#21]
**Is your feature request related to a problem? Please describe.**

This is my favorite theme that I've used, but I am disappointed that there are no visible indent guides. Those vertical lines that match up lines with brackets is such an important visual cue for writing good-looking code to me.

Edit: just realized that they do show up when the cursor is inside of the block, but you can only see the guide of the inner-most block. I would much rather they all just be visible always.

**Describe the solution you'd like**

I would like indent guides to be visible. 

**Additional context**

Perhaps there are guides, but they are just a very dark color that does not stand out well from the background... idk.

Here is 2077:
![2077_noindentguides](https://user-images.githubusercontent.com/9373509/94388154-04ad6680-0101-11eb-842a-c6a32c59886d.png)
As you can see, there are no indent guides.

Here is Dark+:
![Screenshot from 2020-09-27 20-34-36](https://user-images.githubusercontent.com/9373509/94388172-11ca5580-0101-11eb-82cb-e8b49911071b.png)
You can see the vertical lines that connect line 49 to line 64 and the ones between the if statement blocks (line 55-57 and 58-60).

I hope you consider implementing this feature. I would greatly appreciate it. Thank you!

**Comment by kybouw** [comment]
I just found out that you can customize themes. Adding this to my settings.json fixed the issue:
```json
"workbench.colorCustomizations": {
    "[2077]": {
        "editorIndentGuide.background": "#103483"
    }
}
```

**Comment by endormi** [comment]
Ok 👍. I removed indent guides due to my personal choice, but if more people want it, i'll add it. I'm glad you could customize it.
