### ISSUE TITLE
Color Improvement Request

### ISSUE THREAD

**Issue by mrdrwest** [endormi/vscode-2077-theme#22]
**Is your feature request related to a problem? Please describe.**
Text highlighting can be difficult to see, not enough contrast. 

**Describe the solution you'd like**
Improve the contrast of text highlighting.
It would be nice if some attributes could be modified e.g. node line color, text highlighting, via a configuration file.

**Additional context**
![image](https://user-images.githubusercontent.com/12753085/97112875-2e848980-16bd-11eb-8aaf-98cefe43391b.png)

**Comment by endormi** [comment]
Ok 👍, I will look into it. This was actually something I have thought of before, but I don't want it to be too light.

Any color ideas? Or just a lighter color?

**Comment by endormi** [comment]
FYI i'm going back an forth on whether this should be added

**Comment by endormi** [comment]
I tried changing the color to a more lighter one and in my opinion it's too light. 

I am closing this issue, but feel free to open it if you're not happy with my choice. Also you could fork this theme and make the edit yourself.

Thanks for using this theme!
