### ISSUE TITLE
Better highlighting for JSX

### ISSUE THREAD

**Issue by halented** [endormi/vscode-2077-theme#23]
**Is your feature request related to a problem? Please describe.**
When writing React components often the highlighting for the theme is almost 100% pink -- no differences between divs/objects/properties. Screenshot here:
![Poor JSX highlighting example](https://i.imgur.com/ltwTJPH.png)

**Describe the solution you'd like**
Color changes for different code operations in JSX such as varied highlighting for HTML tags, variables, and properties

**Additional context**
Thank u for making this theme I love this it overall

**Comment by endormi** [comment]
Thanks for the request!

I will be working on this, expect a new version release this week.

**Comment by endormi** [comment]
I added the new `v.1.4.9`, if you think this doesn't look good feel free to re-open this issue.

Thanks for using this theme!
