### ISSUE TITLE
Open VSX Support

### ISSUE THREAD

**Issue by chaosharmonic** [endormi/vscode-2077-theme#24]
Hey there - any way you'd be willing to publish this to the Open VSX Registry? It would make this accessible to downstream projects like Theia and VSCodium, which can't access the VS Code Marketplace for licensing reasons. (In particular, various Arch Linux distros ship with Code-OSS builds by default.)

Here's a link to [some relevant documentation from the OVSX wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by endormi** [comment]
Thanks for the request and great idea!

I'm not at all familiar with Open VSX Registry, but I will be publishing this theme.

**Comment by endormi** [comment]
Published [Open VSX Registry](https://open-vsx.org/extension/Endormi/2077-theme).

**Comment by chaosharmonic** [comment]
Awesome! Thanks ^^
