### ISSUE TITLE
any plans to webstorm version?

### ISSUE THREAD

**Issue by rodrigozayit** [endormi/vscode-2077-theme#26]
just an idea.. Jet Brains IDEs <3

**Comment by endormi** [comment]
Thanks for the suggestion! 

I'm not sure, I'll have to think about it. I will let you know later.

**Comment by endormi** [comment]
Hey, sorry for the long wait. 

I'm not familiar with Jet Brains IDEs and do not plan on using them, so I'll pass on this.
Thanks again for the suggestion.
