### ISSUE TITLE
Customize theme

### ISSUE THREAD

**Issue by endormi** [endormi/vscode-2077-theme#27]
Hey, to anyone that is reading this message!

If there are certain aspects of the theme that you don't like, you don't need to use a different theme.
I just wanted to make a disclaimer about letting you know that this theme can be customized.

Just as an example. talking about #21 I personally enjoy not having indent guides, but someone else might not.

If you want to make some bigger changes, you can just clone this project without having to fork it and make the updates to the theme and then add the theme locally to your `.vscode/extensions` folder. 

If you only have a few changes, you can add your customizations to `settings.json` file like this (copied from example issue):

```
"workbench.colorCustomizations": {
    "[2077]": {
        "editorIndentGuide.background": "#103483"
    }
}
``` 

[Example on how to work with settings.json](https://supunkavinda.blog/vscode-editing-settings-json).

**Comment by Hugocorreaa** [comment]
thank you
