### ISSUE TITLE
Font used in the Preview Image

### ISSUE THREAD

**Issue by naveganth** [endormi/vscode-2077-theme#29]
I would like to know what font you in the preview image of the 2077 Theme, and how to install it.
![image](https://github.com/endormi/vscode-2077-theme/assets/159157666/b25891b1-09b3-402a-bb98-f6228772f558)

**Comment by endormi** [comment]
Sorry I meant to answer this earlier, but ended up forgetting. 
The font-family is `"Operator Mono, Menlo, Monaco, 'Courier New', monospace",`.

You shouldn't need to install those fonts.

**Comment by naveganth** [comment]
Thanks @endormi
