### ISSUE TITLE
Selection blends in with the background

### ISSUE THREAD

**Issue by AnecAllods** [endormi/vscode-2077-theme#3]
When selecting the color is not clear enough to distinguish from the background it kind of blends in its hard to tell what is selected and whats not.

recommend offsetting it to a light gray or something more vibrant that makes sense with the theme

**Comment by endormi** [comment]
Thanks 👍, I'll look into it ASAP

**Comment by endormi** [comment]
I might select a lighter blue, since the theme already has light blue in it.

**Comment by endormi** [comment]
fixed https://github.com/endormi/vscode-2077-theme/releases/tag/v.1.0.3
