### ISSUE TITLE
Javascript colours

### ISSUE THREAD

**Issue by fmercerat** [endormi/vscode-2077-theme#5]
Not an issue, it's a request.
In Javascript:
When you write `var foo = 'bar';`  var and foo has the same colours, It would be great if var has a colour and foo a different colour

**Comment by endormi** [comment]
Thanks for the request! I'll have to look into it.

**Comment by endormi** [comment]
https://github.com/endormi/vscode-2077-theme/releases/tag/v.1.2.2

I used a lightpurple color.
