### ISSUE TITLE
Function definition peek window

### ISSUE THREAD

**Issue by iamhasansayani** [endormi/vscode-2077-theme#7]
Kudos! Awesome theme. It is my default now.
Minor tweak needed.

The function definition peek window has background as white. It make it a little to bright for the fonts color scheme. Can you change it to something a bit darker?

**Comment by endormi** [comment]
Thanks for using this theme! I'll look into it ASAP.

**Comment by endormi** [comment]
Can you give me a photo example?

**Comment by endormi** [comment]
If I understand correctly

![snip](https://user-images.githubusercontent.com/39559256/64063761-75820680-cc01-11e9-8421-dfeac3a8c725.PNG)

do you mean the highlight?

If you do this was an issue before and I fixed it with choosing a lighter color. https://github.com/endormi/vscode-2077-theme/issues/3

**Comment by iamhasansayani** [comment]
thanks for the theme! it makes reading code so much better. Kudos!

**Comment by endormi** [comment]
No problem! Thanks for using it :smile:
